// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Base() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Minecraft Network Admin</title><link rel=\"stylesheet\" href=\"/static/styles.css\"><script src=\"https://unpkg.com/htmx.org@1.9.10\" integrity=\"sha384-D1Kt99CQMDuChtQLs1iDriKAxLwkkZaWVMnbxKf9TiQLSrpX+M6WwWP3gNbhJTw\" crossorigin=\"anonymous\"></script><script src=\"https://unpkg.com/htmx.org/dist/ext/method-override.js\"></script></head><body class=\"bg-gray-100 font-sans leading-normal tracking-normal\"><nav class=\"bg-blue-600 p-4 text-white\"><div class=\"container mx-auto flex justify-between items-center\"><a href=\"/\" class=\"text-2xl font-bold\">Minecraft Admin</a><div><button class=\"nav-link\" hx-get=\"/players\" hx-target=\"#content\" hx-swap=\"innerHTML\">Players</button> <button class=\"nav-link\" hx-get=\"/servers\" hx-target=\"#content\" hx-swap=\"innerHTML\">Servers</button> <button class=\"nav-link\" hx-get=\"/policies\" hx-target=\"#content\" hx-swap=\"innerHTML\">Policies</button></div></div></nav><main class=\"container mx-auto mt-8 p-4\"><div id=\"content\" class=\"bg-white p-6 rounded-lg shadow-md\"><h1 class=\"text-3xl font-bold mb-4\">Welcome to the Minecraft Network Admin Panel!</h1><p>Use the navigation above to manage players, servers, and permissions.</p></div></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
