# {{- if and .Values.permissionsWebapp.enabled .Values.permissionsWebapp.ingress.enabled }}
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: {{ include "network.fullname" . }}-perms-webapp
#   labels:
#     {{- include "network.labels" . | nindent 4 }}
#     app.kubernetes.io/component: permissions-webapp
#   {{- with .Values.permissionsWebapp.ingress.annotations }}
#   annotations:
#     {{- toYaml . | nindent 4 }}
#   {{- end }}
# spec:
#   {{- if .Values.permissionsWebapp.ingress.className }}
#   ingressClassName: {{ .Values.permissionsWebapp.ingress.className }}
#   {{- end }}
#   {{- if .Values.permissionsWebapp.ingress.tls }}
#   tls:
#     {{- range .Values.permissionsWebapp.ingress.tls }}
#     - hosts:
#         {{- range .hosts }}
#         - {{ . | quote }}
#         {{- end }}
#       secretName: {{ .secretName }}
#     {{- end }}
#   {{- end }}
#   rules:
#     {{- range .Values.permissionsWebapp.ingress.hosts }}
#     - host: {{ .host | quote }}
#       http:
#         paths:
#           {{- range .paths }}
#           - path: {{ .path }}
#             pathType: {{ .pathType }}
#             backend:
#               service:
#                 name: {{ include "network.fullname" $ }}-perms-webapp
#                 port:
#                   name: http # Or number: {{ $.Values.permissionsWebapp.service.port }}
#           {{- end }}
#     {{- end }}
# {{- end }}
