apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yaml
  - service.yaml


labels:
  - pairs:
      app.kubernetes.io/name: permissions-checker
      app.kubernetes.io/component: auth-service
    includeSelectors: true
    includeTemplates: true
