apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yaml
  - service.yaml

configMapGenerator:
  - name: proxy-config
    files:
      - gate-config.yaml
    options:
      disableNameSuffixHash: true


labels:
  - pairs:
      app.kubernetes.io/name: gate-proxy
      app.kubernetes.io/component: proxy
    includeSelectors: true
    includeTemplates: true
