apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  ports:
    - port: 25565
      targetPort: minecraft
      nodePort: 30000
      name: minecraft
      protocol: TCP
  type: "{{ get_var(['proxy.serviceType'], 'NodePort') }}"
