apiVersion: templates.kluctl.io/v1alpha1
kind: ObjectTemplate
metadata:
  name: postgres-secret-transformer
spec:
  serviceAccountName: postgres-secret-transformer
  prune: true
  matrix:
    - name: secret
      object:
        ref:
          apiVersion: v1
          kind: Secret
          name: "{{ user }}.{{ cluster_name }}.credentials.postgresql.acid.zalan.do"
  templates:
  - object:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "permify-postgres-secret"
      stringData:
        uri: "postgres://{{ '{{ matrix.secret.data.username | b64decode }}' }}:{{ '{{ matrix.secret.data.password | b64decode }}' }}@{{ cluster_name }}.{{ namespace }}.svc.cluster.local:5432/{{ database }}?sslmode=require"
