apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - proxy-secret.yaml

configMapGenerator:
  - name: casbin-model
    files:
      - permissions_model.conf
    options:
      disableNameSuffixHash: true
